### ISSUE TITLE
Is there any reason why SimpleCharStream and JavaCharStream buffer themselves?

### ISSUE THREAD

**Issue by phax** [phax/ParserGeneratorCC#13]
Why don't they use `PushBackReader`?
This whole setup seems to be a bit overly complex (or grown over time?).
I would like to cut this down to a simple reader using a `PushBackReader` acting on top of a `BufferedReader` or so

Any comments @matozoid @ftomasetti

**Comment by matozoid** [comment]
I really have no idea!

**Comment by phax** [comment]
Basically the same issue as #21
