### ISSUE TITLE
Why not contribute to javacc/javacc?

### ISSUE THREAD

**Issue by eduarddrenth** [phax/ParserGeneratorCC#15]
I would prefer just one maintained javacc and just one maintained maven plugin that uses that.

Is the code quality argument a strong enough case to justify separate development?

By the way it is good to see some new life in javacc, it would be nice to see a community growing around it.

**Comment by phax** [comment]
In general I fully agree. But the guy from javacc is very reluctant in applying PRs and this makes it very tedious, as I'm personally also relying on JavaCC in other projects.
Unfortunately I don't have too much time to fiddle with PGCC currently but of course I will tackle the escaping issue ASAP.

**Comment by eduarddrenth** [comment]
ok, lingering is bad. Thanks.

**Comment by revusky** [comment]
I think that this blog post answers the question posed: https://javacc.com/2020/10/28/a-bugs-life/

**Comment by eduarddrenth** [comment]
wow
