### ISSUE TITLE
Question on this project

### ISSUE THREAD

**Issue by ftomassetti** [phax/ParserGeneratorCC#17]
Hi folks!
I have a few questions on the project. In particular I would like to understand how hard would be for a project to switch from JavaCC to ParserGeneratorCC. 

In particular:

* is the syntax any different?
* do you have a maven plugin to invoke ParserGeneratorCC?

Beside that I would like to see if some features could be supported. My intent would be to make an [extensible parser](https://github.com/javaparser/javaparser/issues/1811). 

To do so I would need the generated parser and some methods to not be marked as final. Would that be possible?

**Comment by phax** [comment]
* The syntax is totally identical
* The focus is to deliver better generated code (especially for easier maintenance)
* Get rid of all the Java 1.6 stuff
* Current version is used in ph-javacc-maven-plugin and nobody noticed (?) the different.

**Comment by ftomassetti** [comment]
I tried moving to version 4.0.3 of ph-javacc-maven-plugin, therefore using ParserGeneratorCC instead of JavaCC in JavaParser. No changes needed so I can confirm that the effort of migrating is simply zero :)
