### ISSUE TITLE
Remove encoding-less parser constructors

### ISSUE THREAD

**Issue by sfuhrm** [phax/ParserGeneratorCC#29]
ph-javacc-maven-plugin warns in the docs about the constructors without an encoding.

The parser constructors without a character encoding throw a NullPointerException.

It doesn't make sense to keep these calls since they are breaking the API because the encoding is now mandatory. Before that, it seems to have been assigned by default if no encoding was given.

I'd suggest to remove the parser constructor calls without character encoding.

This is the exception that is thrown when calling the 'buggy constructors':

```
Caused by: java.lang.NullPointerException: charsetName
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:99)
        at de.einsundeins.netcfg.preprocessor.templatepreprocessor.SimpleCharStream.<init>(SimpleCharStream.java:69)
        at de.einsundeins.netcfg.preprocessor.templatepreprocessor.SimpleCharStream.<init>(SimpleCharStream.java:78)
        at de.einsundeins.netcfg.preprocessor.templatepreprocessor.TemplatePreprocessor.<init>(TemplatePreprocessor.java:263)
        at de.einsundeins.netcfg.preprocessor.templatepreprocessor.TemplatePreprocessor.<init>(TemplatePreprocessor.java:253)
        .....
```

**Comment by phax** [comment]
Well, alternatively I could fix the NullPointerException ;-)

**Comment by sfuhrm** [comment]
Thanks for quick response :+1: 

InputStreams deliver bytes, not chars. But a parser needs chars. So I think it makes sense to either go with a Reader or an InputStream+encoding.

Since the problematic calls are using an InputStream as the source, it would be better to drop the variants without encoding all over. I'd go one step further and make all InputStream constructors only a mapping to some meaningful Reader instance.

I guess the old JavaCC code guessed (!?) what the encoding is. Guessing is bad.

I had the NPE-behaviour in old code that used JavaCC before and was a bit surprised that I get runtime errors after migrating to ph-javacc-maven-plugin (thanks for that!).

My opinion: Compile time errors are much better if you need to touch your code anyway.

**Comment by phax** [comment]
Hi,
so I scanned through the sources and could not find any template that contains a constructor without a charset.
What version of the ph-javacc-maven-plugin / parser-generator-cc are you using?
The latest versions are 4.1.4 (ph-javacc-maven-plugin) and 1.1.3 (parser-generator-cc)
Sorry for looking dumb ;-)

**Comment by sfuhrm** [comment]
Never mind, we're here to master complexity ;)

The plugin used is 4.1.4:

```xml
      <plugin>
        <groupId>com.helger.maven</groupId>
        <artifactId>ph-javacc-maven-plugin</artifactId>
        <version>4.1.4</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <id>javacc</id>
            <goals>
              <goal>javacc</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

and this uses

```xml
    <dependency>
      <groupId>com.helger</groupId>
      <artifactId>parser-generator-cc</artifactId>
      <version>1.1.3</version>
    </dependency>
```

**Comment by sfuhrm** [comment]
I think you are looking for [this](https://github.com/phax/ParserGeneratorCC/blob/eac976027a412a850a30857757fe5c8f91c3f88e/src/main/java/com/helger/pgcc/parser/ParseGenJava.java#L340) ?

**Comment by phax** [comment]
Ahhhh :D - thank you ;-) Too many configuration options. 😊

**Comment by phax** [comment]
Since I always use "modern" mode I never stumbled upon that one.... *sigh*
